# Site settings
title: Jon Dean
description: > # this means to ignore newlines until "baseurl:"
  Jon Dean, Principal Engineer at Stitch Fix
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathandean.com" # the base hostname & protocol for your site
twitter_username: jonathanedean
github_username:  jonathandean

# Build settings
markdown: kramdown

# Style of permalinks
permalink: /:year/:month/:title

exclude:
  - "bower_components"
  - "bower.json"