# This will be the first part of the title tag for your site <title> site.name + page.title </title>
name: "Jonathan Dean"
# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
description: "Jonathan Dean - Web Software Engineer"

# Owner (organization or individual) of site content
author: "jonathandean"

excerpt_separator: "<!--more-->"

#url: "[http:// ]"
url: "http://jonathandean.com"

# Your UA tracking number (i.e 35858753-1) for Google Analytics. 
# If you comment this out, or don't fill out this parameter - Google analytics won't be included. 
googleID: 

# Pagination variable for how many posts to show in a list
paginate: 5

# Style of permalinks
permalink: /:year/:month/:title

# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:yearr/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

# If you want to display social nav - fill out the appropriate handles. Delete or comment out unneeded networks. 
github: ""
twitter: ""
instagram: ""
dribbble: ""
soundcloud: ""
flickr: ""

# UnComment once you have pygments installed. Used for code syntax highlighting.
highlighter: 'pygments'

markdown: kramdown

exclude: [Rakefile]
